import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import Adsense from "./components/Adsense";

export const metadata: Metadata = {
  title: "YappingGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Adsense pId={process.env.Ad_API!} />
      </head>
      <body className={`antialiased`}>{children}</body>
      <Analytics />
    </html>
  );
}
